### ISSUE TITLE
Add EJML to project

### ISSUE THREAD

**Issue by jee7s** [frc6357/robot_code_2018#4]
We need EJML added to support development on the kf_dev branch.

JAR file here:
https://sourceforge.net/projects/ejml/?source=typ_redirect

**Comment by dawilson9** [comment]
I've added EJML 0.34 to the tree under robotcode/ejml-v0.34-libs. This is currently in the develop branch. Feel free to cherry pick onto whichever branch you create (I don't see a kf_dev branch yet).

**Comment by jee7s** [comment]
I'll be pushing it later tonight. Thanks for the quick response.

**Comment by dawilson9** [comment]
I've just pushed changes to the develop branch which add ejml-core and ejml-simple libraries to the project. With this change, the KalmanFIlter1D class now builds cleanly.
