### ISSUE TITLE
Check Voltage Levels for UART vs RS-232

### ISSUE THREAD

**Issue by jee7s** [frc6357/robot_code_2018#6]
Related to the review in PR #5 we should check the voltage levels on the RS-232 port and the UART on the MXP. If the RS-232 is indeed true TIA-232, then the signal level of the TFmini (3.3V) is too small to work with the port. We may need to solder on to the MXP serial port on the IMU board to get a connection with suitable voltage levels.

**Comment by dawilson9** [comment]
If the RoboRio RS232 complies with TIA/EIA-232-F them we’ll need to use the other UART. The TFmini uses 0-3.3V signaling but TIA/EIA-232-F specifies negative and positive voltage signaling between 5V and 15V.

**Comment by dawilson9** [comment]
BTW, I checked both specs. Re-readings previous comment it could be read as a question rather than a statement :-)

**Comment by dawilson9** [comment]
When we move the connection to the MXP serial port, the code needs to modify the second parameter to the SerialPort constructor to be SerialPort.kMXP.

**Comment by dawilson9** [comment]
I've modified the TFMini class to use the MXP serial port. Code is pushed. Leaving the problem open until whoever is next playing with the hardware moves the LIDAR connection to the MXP port.

**Comment by dawilson9** [comment]
After another look through the data sheet for the TFMini, I think I see another error. The parity setting is listed as "0" which I took to mean "no parity bit". More likely, however, this mean space parity (parity bit always transmitted as 0) so I've modified the TFMini class to use this setting.

**Comment by jee7s** [comment]
Today's test confirmed the TFMini was signalling as expected. Per the TFMini datasheet, the signal level is 3.3V. Since we saw the signals on the logic analyzer, this points strongly to the port being true TIA-232. The soldered mod to the IMU board should address this.
